#pragma once

/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <windows.h>
#include <Thrift/Thrift.h>
#include <Thrift/Protocol.h>
#include <Thrift/Transport.h>
#include <Evernote/EDAM/Limits.h>

namespace Evernote
{
namespace EDAM
{
namespace Types
{
class Constants
{
public:
	Constants();

	Thrift::Protocol::TString EDAM_NOTE_SOURCE_WEB_CLIP;
	Thrift::Protocol::TString EDAM_NOTE_SOURCE_MAIL_CLIP;
	Thrift::Protocol::TString EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY;
};
const Constants constants;
} // Types
} // EDAM
} // Evernote
