/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include "../Types.h"
#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <windows.h>
#include <Thrift/Thrift.h>
#include <Thrift/Protocol.h>
#include <Thrift/Transport.h>
#include <Evernote/EDAM/Limits.h>

using namespace Evernote::EDAM::Types;

Constants::Constants()
{
	EDAM_NOTE_SOURCE_WEB_CLIP = Thrift::Protocol::TString(L"web.clip");

	EDAM_NOTE_SOURCE_MAIL_CLIP = Thrift::Protocol::TString(L"mail.clip");

	EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY = Thrift::Protocol::TString(L"mail.smtp");

}
