/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include "../Types.h"
#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <windows.h>
#include <Thrift/Thrift.h>
#include <Thrift/Protocol.h>
#include <Thrift/Transport.h>
#include <Evernote/EDAM/Limits.h>

using namespace Evernote::EDAM::Types;

NoteAttributes::NoteAttributes()
{
	memset(&__isset, 0, sizeof(Isset));
}

void NoteAttributes::Read(Thrift::Protocol::TProtocol & iprot)
{
	Thrift::Protocol::TStruct struc;
	iprot.ReadStructBegin(struc);
	for (;;)
	{
		Thrift::Protocol::TField field;
		iprot.ReadFieldBegin(field);
		if (field.GetType() == Thrift::Protocol::TypeStop)
			break;
		switch (field.GetID())
		{
		case 1:
			if (field.GetType() == Thrift::Protocol::TypeI64)
			{
				this->subjectDate = iprot.ReadI64();
				this->__isset.subjectDate = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 10:
			if (field.GetType() == Thrift::Protocol::TypeDouble)
			{
				this->latitude = iprot.ReadDouble();
				this->__isset.latitude = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 11:
			if (field.GetType() == Thrift::Protocol::TypeDouble)
			{
				this->longitude = iprot.ReadDouble();
				this->__isset.longitude = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 12:
			if (field.GetType() == Thrift::Protocol::TypeDouble)
			{
				this->altitude = iprot.ReadDouble();
				this->__isset.altitude = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 13:
			if (field.GetType() == Thrift::Protocol::TypeString)
			{
				this->author;
				iprot.ReadString(this->author);
				this->__isset.author = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 14:
			if (field.GetType() == Thrift::Protocol::TypeString)
			{
				this->source;
				iprot.ReadString(this->source);
				this->__isset.source = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 15:
			if (field.GetType() == Thrift::Protocol::TypeString)
			{
				this->sourceURL;
				iprot.ReadString(this->sourceURL);
				this->__isset.sourceURL = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 16:
			if (field.GetType() == Thrift::Protocol::TypeString)
			{
				this->sourceApplication;
				iprot.ReadString(this->sourceApplication);
				this->__isset.sourceApplication = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		default: 
			Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			break;
		}
		iprot.ReadFieldEnd();
	}
	iprot.ReadStructEnd();
}

void NoteAttributes::Write(Thrift::Protocol::TProtocol & oprot)
{
	Thrift::Protocol::TStruct struc;
	struc.SetName(L"NoteAttributes");
	oprot.WriteStructBegin(struc);
	if (__isset.subjectDate)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"subjectDate");
		field.SetType(Thrift::Protocol::TypeI64);
		field.SetID(1);
		oprot.WriteFieldBegin(field);
		oprot.WriteI64(this->subjectDate);
		oprot.WriteFieldEnd();
	}
	if (__isset.latitude)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"latitude");
		field.SetType(Thrift::Protocol::TypeDouble);
		field.SetID(10);
		oprot.WriteFieldBegin(field);
		oprot.WriteDouble(this->latitude);
		oprot.WriteFieldEnd();
	}
	if (__isset.longitude)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"longitude");
		field.SetType(Thrift::Protocol::TypeDouble);
		field.SetID(11);
		oprot.WriteFieldBegin(field);
		oprot.WriteDouble(this->longitude);
		oprot.WriteFieldEnd();
	}
	if (__isset.altitude)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"altitude");
		field.SetType(Thrift::Protocol::TypeDouble);
		field.SetID(12);
		oprot.WriteFieldBegin(field);
		oprot.WriteDouble(this->altitude);
		oprot.WriteFieldEnd();
	}
	if (__isset.author)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"author");
		field.SetType(Thrift::Protocol::TypeString);
		field.SetID(13);
		oprot.WriteFieldBegin(field);
		oprot.WriteString(this->author);
		oprot.WriteFieldEnd();
	}
	if (__isset.source)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"source");
		field.SetType(Thrift::Protocol::TypeString);
		field.SetID(14);
		oprot.WriteFieldBegin(field);
		oprot.WriteString(this->source);
		oprot.WriteFieldEnd();
	}
	if (__isset.sourceURL)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"sourceURL");
		field.SetType(Thrift::Protocol::TypeString);
		field.SetID(15);
		oprot.WriteFieldBegin(field);
		oprot.WriteString(this->sourceURL);
		oprot.WriteFieldEnd();
	}
	if (__isset.sourceApplication)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"sourceApplication");
		field.SetType(Thrift::Protocol::TypeString);
		field.SetID(16);
		oprot.WriteFieldBegin(field);
		oprot.WriteString(this->sourceApplication);
		oprot.WriteFieldEnd();
	}
	oprot.WriteFieldStop();
	oprot.WriteStructEnd();
}

