/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include "../NoteStore.h"
#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <windows.h>
#include <Thrift/Thrift.h>
#include <Thrift/Protocol.h>
#include <Thrift/Transport.h>
#include <Evernote/EDAM/UserStore.h>
#include <Evernote/EDAM/Type.h>
#include <Evernote/EDAM/Error.h>
#include <Evernote/EDAM/Limits.h>

using namespace Evernote::EDAM::NoteStore;

AdParameters::AdParameters()
{
	::ZeroMemory(&__isset, sizeof(Isset));
}

void AdParameters::Read(Thrift::Protocol::TProtocol & iprot)
{
	Thrift::Protocol::TStruct struc;
	iprot.ReadStructBegin(struc);
	for (;;)
	{
		Thrift::Protocol::TField field;
		iprot.ReadFieldBegin(field);
		if (field.GetType() == Thrift::Protocol::TypeStop)
			break;
		switch (field.GetID())
		{
		case 2:
			if (field.GetType() == Thrift::Protocol::TypeString)
			{
				iprot.ReadString(this->clientLanguage);
				this->__isset.clientLanguage = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 4:
			if (field.GetType() == Thrift::Protocol::TypeList)
			{
				{
					Thrift::Protocol::TList _list86;
					iprot.ReadListBegin(_list86);
					for (int _i87 = 0; _i87 < _list86.GetCount(); ++_i87)
					{
						AdImpressions _elem88;
						_elem88.Read(iprot);
						this->impressions.push_back(_elem88);
					}
					iprot.ReadListEnd();
				}
				this->__isset.impressions = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 5:
			if (field.GetType() == Thrift::Protocol::TypeBool)
			{
				this->supportHtml = iprot.ReadBool();
				this->__isset.supportHtml = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 6:
			if (field.GetType() == Thrift::Protocol::TypeMap)
			{
				{
					Thrift::Protocol::TMap _map89;
					iprot.ReadMapBegin(_map89);
					for (int _i90 = 0; _i90 < _map89.GetCount(); ++_i90)
					{
						Thrift::Protocol::TString _key91;
						Thrift::Protocol::TString _val92;
						iprot.ReadString(_key91);
						iprot.ReadString(_val92);
						this->clientProperties[_key91] = _val92;
					}
					iprot.ReadMapEnd();
				}
				this->__isset.clientProperties = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		default: 
			Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			break;
		}
		iprot.ReadFieldEnd();
	}
	iprot.ReadStructEnd();
}

void AdParameters::Write(Thrift::Protocol::TProtocol & oprot)
{
	Thrift::Protocol::TStruct struc;
	struc.SetName(L"AdParameters");
	oprot.WriteStructBegin(struc);
	if (__isset.clientLanguage)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"clientLanguage");
		field.SetType(Thrift::Protocol::TypeString);
		field.SetID(2);
		oprot.WriteFieldBegin(field);
		oprot.WriteString(this->clientLanguage);
		oprot.WriteFieldEnd();
	}
	if (__isset.impressions)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"impressions");
		field.SetType(Thrift::Protocol::TypeList);
		field.SetID(4);
		oprot.WriteFieldBegin(field);
		{
			Thrift::Protocol::TList list;
			list.SetElementType(Thrift::Protocol::TypeStruct);
			list.SetCount(this->impressions.size());
			oprot.WriteListBegin(list);
			for (std::vector<AdImpressions >::iterator _iter93(this->impressions.begin()), end(this->impressions.end()); _iter93 != end; ++_iter93)
			{
				(*_iter93).Write(oprot);
				oprot.WriteListEnd();
			}
		}
		oprot.WriteFieldEnd();
	}
	if (__isset.supportHtml)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"supportHtml");
		field.SetType(Thrift::Protocol::TypeBool);
		field.SetID(5);
		oprot.WriteFieldBegin(field);
		oprot.WriteBool(this->supportHtml);
		oprot.WriteFieldEnd();
	}
	if (__isset.clientProperties)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"clientProperties");
		field.SetType(Thrift::Protocol::TypeMap);
		field.SetID(6);
		oprot.WriteFieldBegin(field);
		{
			Thrift::Protocol::TMap map;
			map.SetKeyType(Thrift::Protocol::TypeString);
			map.SetValueType(Thrift::Protocol::TypeString);
			map.SetCount(this->clientProperties.size());
			oprot.WriteMapBegin(map);
			for (std::map<Thrift::Protocol::TString, Thrift::Protocol::TString >::iterator _iter94(this->clientProperties.begin()), end(this->clientProperties.end()); _iter94 != end; ++_iter94)
			{
				oprot.WriteString(_iter94->first);
				oprot.WriteString(_iter94->second);
				oprot.WriteMapEnd();
			}
		}
		oprot.WriteFieldEnd();
	}
	oprot.WriteFieldStop();
	oprot.WriteStructEnd();
}

