#pragma once

/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <windows.h>
#include <Thrift/Thrift.h>
#include <Thrift/Protocol.h>
#include <Thrift/Transport.h>
#include <Evernote/EDAM/UserStore.h>
#include <Evernote/EDAM/Types.h>
#include <Evernote/EDAM/Error.h>
#include <Evernote/EDAM/Limits.h>


namespace Evernote
{
namespace EDAM
{
namespace NoteStore
{

class AdParameters
{
public:

	struct Isset
	{
		bool clientLanguage;
		bool impressions;
		bool supportHtml;
		bool clientProperties;
	};

	Thrift::Protocol::TString clientLanguage;
	std::vector<AdImpressions > impressions;
	bool supportHtml;
	std::map<Thrift::Protocol::TString, Thrift::Protocol::TString > clientProperties;

	Isset __isset;

	AdParameters();
	virtual ~AdParameters() throw() {}

	void Read(Thrift::Protocol::TProtocol & iprot);
	void Write(Thrift::Protocol::TProtocol & oprot);
};
} // NoteStore
} // EDAM
} // Evernote
