/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include "../NoteStore.h"
#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <windows.h>
#include <Thrift/Thrift.h>
#include <Thrift/Protocol.h>
#include <Thrift/Transport.h>
#include <Evernote/EDAM/UserStore.h>
#include <Evernote/EDAM/Type.h>
#include <Evernote/EDAM/Error.h>
#include <Evernote/EDAM/Limits.h>

using namespace Evernote::EDAM::NoteStore;

NotesMetadataList::NotesMetadataList()
{
	::ZeroMemory(&__isset, sizeof(Isset));
}

void NotesMetadataList::Read(Thrift::Protocol::TProtocol & iprot)
{
	Thrift::Protocol::TStruct struc;
	iprot.ReadStructBegin(struc);
	for (;;)
	{
		Thrift::Protocol::TField field;
		iprot.ReadFieldBegin(field);
		if (field.GetType() == Thrift::Protocol::TypeStop)
			break;
		switch (field.GetID())
		{
		case 1:
			if (field.GetType() == Thrift::Protocol::TypeI32)
			{
				this->startIndex = iprot.ReadI32();
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 2:
			if (field.GetType() == Thrift::Protocol::TypeI32)
			{
				this->totalNotes = iprot.ReadI32();
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 3:
			if (field.GetType() == Thrift::Protocol::TypeList)
			{
				{
					Thrift::Protocol::TList _list64;
					iprot.ReadListBegin(_list64);
					for (int _i65 = 0; _i65 < _list64.GetCount(); ++_i65)
					{
						NoteMetadata _elem66;
						_elem66.Read(iprot);
						this->notes.push_back(_elem66);
					}
					iprot.ReadListEnd();
				}
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 4:
			if (field.GetType() == Thrift::Protocol::TypeList)
			{
				{
					Thrift::Protocol::TList _list67;
					iprot.ReadListBegin(_list67);
					for (int _i68 = 0; _i68 < _list67.GetCount(); ++_i68)
					{
						Thrift::Protocol::TString _elem69;
						iprot.ReadString(_elem69);
						this->stoppedWords.push_back(_elem69);
					}
					iprot.ReadListEnd();
				}
				this->__isset.stoppedWords = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 5:
			if (field.GetType() == Thrift::Protocol::TypeList)
			{
				{
					Thrift::Protocol::TList _list70;
					iprot.ReadListBegin(_list70);
					for (int _i71 = 0; _i71 < _list70.GetCount(); ++_i71)
					{
						Thrift::Protocol::TString _elem72;
						iprot.ReadString(_elem72);
						this->searchedWords.push_back(_elem72);
					}
					iprot.ReadListEnd();
				}
				this->__isset.searchedWords = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 6:
			if (field.GetType() == Thrift::Protocol::TypeI32)
			{
				this->updateCount = iprot.ReadI32();
				this->__isset.updateCount = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		default: 
			Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			break;
		}
		iprot.ReadFieldEnd();
	}
	iprot.ReadStructEnd();
}

void NotesMetadataList::Write(Thrift::Protocol::TProtocol & oprot)
{
	Thrift::Protocol::TStruct struc;
	struc.SetName(L"NotesMetadataList");
	oprot.WriteStructBegin(struc);
	{
		Thrift::Protocol::TField field;
		field.SetName(L"startIndex");
		field.SetType(Thrift::Protocol::TypeI32);
		field.SetID(1);
		oprot.WriteFieldBegin(field);
		oprot.WriteI32(this->startIndex);
		oprot.WriteFieldEnd();
	}
	{
		Thrift::Protocol::TField field;
		field.SetName(L"totalNotes");
		field.SetType(Thrift::Protocol::TypeI32);
		field.SetID(2);
		oprot.WriteFieldBegin(field);
		oprot.WriteI32(this->totalNotes);
		oprot.WriteFieldEnd();
	}
	{
		Thrift::Protocol::TField field;
		field.SetName(L"notes");
		field.SetType(Thrift::Protocol::TypeList);
		field.SetID(3);
		oprot.WriteFieldBegin(field);
		{
			Thrift::Protocol::TList list;
			list.SetElementType(Thrift::Protocol::TypeStruct);
			list.SetCount(this->notes.size());
			oprot.WriteListBegin(list);
			for (std::vector<NoteMetadata >::iterator _iter73(this->notes.begin()), end(this->notes.end()); _iter73 != end; ++_iter73)
			{
				(*_iter73).Write(oprot);
				oprot.WriteListEnd();
			}
		}
		oprot.WriteFieldEnd();
	}
	if (__isset.stoppedWords)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"stoppedWords");
		field.SetType(Thrift::Protocol::TypeList);
		field.SetID(4);
		oprot.WriteFieldBegin(field);
		{
			Thrift::Protocol::TList list;
			list.SetElementType(Thrift::Protocol::TypeString);
			list.SetCount(this->stoppedWords.size());
			oprot.WriteListBegin(list);
			for (std::vector<Thrift::Protocol::TString >::iterator _iter74(this->stoppedWords.begin()), end(this->stoppedWords.end()); _iter74 != end; ++_iter74)
			{
				oprot.WriteString((*_iter74));
				oprot.WriteListEnd();
			}
		}
		oprot.WriteFieldEnd();
	}
	if (__isset.searchedWords)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"searchedWords");
		field.SetType(Thrift::Protocol::TypeList);
		field.SetID(5);
		oprot.WriteFieldBegin(field);
		{
			Thrift::Protocol::TList list;
			list.SetElementType(Thrift::Protocol::TypeString);
			list.SetCount(this->searchedWords.size());
			oprot.WriteListBegin(list);
			for (std::vector<Thrift::Protocol::TString >::iterator _iter75(this->searchedWords.begin()), end(this->searchedWords.end()); _iter75 != end; ++_iter75)
			{
				oprot.WriteString((*_iter75));
				oprot.WriteListEnd();
			}
		}
		oprot.WriteFieldEnd();
	}
	if (__isset.updateCount)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"updateCount");
		field.SetType(Thrift::Protocol::TypeI32);
		field.SetID(6);
		oprot.WriteFieldBegin(field);
		oprot.WriteI32(this->updateCount);
		oprot.WriteFieldEnd();
	}
	oprot.WriteFieldStop();
	oprot.WriteStructEnd();
}

