/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include "../NoteStore.h"
#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <windows.h>
#include <Thrift/Thrift.h>
#include <Thrift/Protocol.h>
#include <Thrift/Transport.h>
#include <Evernote/EDAM/UserStore.h>
#include <Evernote/EDAM/Type.h>
#include <Evernote/EDAM/Error.h>
#include <Evernote/EDAM/Limits.h>

using namespace Evernote::EDAM::NoteStore;

NoteList::NoteList()
{
	::ZeroMemory(&__isset, sizeof(Isset));
}

void NoteList::Read(Thrift::Protocol::TProtocol & iprot)
{
	Thrift::Protocol::TStruct struc;
	iprot.ReadStructBegin(struc);
	for (;;)
	{
		Thrift::Protocol::TField field;
		iprot.ReadFieldBegin(field);
		if (field.GetType() == Thrift::Protocol::TypeStop)
			break;
		switch (field.GetID())
		{
		case 1:
			if (field.GetType() == Thrift::Protocol::TypeI32)
			{
				this->startIndex = iprot.ReadI32();
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 2:
			if (field.GetType() == Thrift::Protocol::TypeI32)
			{
				this->totalNotes = iprot.ReadI32();
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 3:
			if (field.GetType() == Thrift::Protocol::TypeList)
			{
				{
					Thrift::Protocol::TList _list48;
					iprot.ReadListBegin(_list48);
					for (int _i49 = 0; _i49 < _list48.GetCount(); ++_i49)
					{
						Evernote::EDAM::Type::Note _elem50;
						_elem50.Read(iprot);
						this->notes.push_back(_elem50);
					}
					iprot.ReadListEnd();
				}
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 4:
			if (field.GetType() == Thrift::Protocol::TypeList)
			{
				{
					Thrift::Protocol::TList _list51;
					iprot.ReadListBegin(_list51);
					for (int _i52 = 0; _i52 < _list51.GetCount(); ++_i52)
					{
						Thrift::Protocol::TString _elem53;
						iprot.ReadString(_elem53);
						this->stoppedWords.push_back(_elem53);
					}
					iprot.ReadListEnd();
				}
				this->__isset.stoppedWords = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 5:
			if (field.GetType() == Thrift::Protocol::TypeList)
			{
				{
					Thrift::Protocol::TList _list54;
					iprot.ReadListBegin(_list54);
					for (int _i55 = 0; _i55 < _list54.GetCount(); ++_i55)
					{
						Thrift::Protocol::TString _elem56;
						iprot.ReadString(_elem56);
						this->searchedWords.push_back(_elem56);
					}
					iprot.ReadListEnd();
				}
				this->__isset.searchedWords = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 6:
			if (field.GetType() == Thrift::Protocol::TypeI32)
			{
				this->updateCount = iprot.ReadI32();
				this->__isset.updateCount = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		default: 
			Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			break;
		}
		iprot.ReadFieldEnd();
	}
	iprot.ReadStructEnd();
}

void NoteList::Write(Thrift::Protocol::TProtocol & oprot)
{
	Thrift::Protocol::TStruct struc;
	struc.SetName(L"NoteList");
	oprot.WriteStructBegin(struc);
	{
		Thrift::Protocol::TField field;
		field.SetName(L"startIndex");
		field.SetType(Thrift::Protocol::TypeI32);
		field.SetID(1);
		oprot.WriteFieldBegin(field);
		oprot.WriteI32(this->startIndex);
		oprot.WriteFieldEnd();
	}
	{
		Thrift::Protocol::TField field;
		field.SetName(L"totalNotes");
		field.SetType(Thrift::Protocol::TypeI32);
		field.SetID(2);
		oprot.WriteFieldBegin(field);
		oprot.WriteI32(this->totalNotes);
		oprot.WriteFieldEnd();
	}
	{
		Thrift::Protocol::TField field;
		field.SetName(L"notes");
		field.SetType(Thrift::Protocol::TypeList);
		field.SetID(3);
		oprot.WriteFieldBegin(field);
		{
			Thrift::Protocol::TList list;
			list.SetElementType(Thrift::Protocol::TypeStruct);
			list.SetCount(this->notes.size());
			oprot.WriteListBegin(list);
			for (std::vector<Evernote::EDAM::Type::Note >::iterator _iter57(this->notes.begin()), end(this->notes.end()); _iter57 != end; ++_iter57)
			{
				(*_iter57).Write(oprot);
				oprot.WriteListEnd();
			}
		}
		oprot.WriteFieldEnd();
	}
	if (__isset.stoppedWords)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"stoppedWords");
		field.SetType(Thrift::Protocol::TypeList);
		field.SetID(4);
		oprot.WriteFieldBegin(field);
		{
			Thrift::Protocol::TList list;
			list.SetElementType(Thrift::Protocol::TypeString);
			list.SetCount(this->stoppedWords.size());
			oprot.WriteListBegin(list);
			for (std::vector<Thrift::Protocol::TString >::iterator _iter58(this->stoppedWords.begin()), end(this->stoppedWords.end()); _iter58 != end; ++_iter58)
			{
				oprot.WriteString((*_iter58));
				oprot.WriteListEnd();
			}
		}
		oprot.WriteFieldEnd();
	}
	if (__isset.searchedWords)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"searchedWords");
		field.SetType(Thrift::Protocol::TypeList);
		field.SetID(5);
		oprot.WriteFieldBegin(field);
		{
			Thrift::Protocol::TList list;
			list.SetElementType(Thrift::Protocol::TypeString);
			list.SetCount(this->searchedWords.size());
			oprot.WriteListBegin(list);
			for (std::vector<Thrift::Protocol::TString >::iterator _iter59(this->searchedWords.begin()), end(this->searchedWords.end()); _iter59 != end; ++_iter59)
			{
				oprot.WriteString((*_iter59));
				oprot.WriteListEnd();
			}
		}
		oprot.WriteFieldEnd();
	}
	if (__isset.updateCount)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"updateCount");
		field.SetType(Thrift::Protocol::TypeI32);
		field.SetID(6);
		oprot.WriteFieldBegin(field);
		oprot.WriteI32(this->updateCount);
		oprot.WriteFieldEnd();
	}
	oprot.WriteFieldStop();
	oprot.WriteStructEnd();
}

