#pragma once

/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <windows.h>
#include <Thrift/Thrift.h>
#include <Thrift/Protocol.h>
#include <Thrift/Transport.h>
#include <Evernote/EDAM/UserStore.h>
#include <Evernote/EDAM/Type.h>
#include <Evernote/EDAM/Error.h>
#include <Evernote/EDAM/Limits.h>


namespace Evernote
{
namespace EDAM
{
namespace NoteStore
{

class NoteList
{
public:

	struct Isset
	{
		bool stoppedWords;
		bool searchedWords;
		bool updateCount;
	};

	__int32 startIndex;
	__int32 totalNotes;
	std::vector<Evernote::EDAM::Type::Note > notes;
	std::vector<Thrift::Protocol::TString > stoppedWords;
	std::vector<Thrift::Protocol::TString > searchedWords;
	__int32 updateCount;

	Isset __isset;

	NoteList();
	virtual ~NoteList() throw() {}

	void Read(Thrift::Protocol::TProtocol & iprot);
	void Write(Thrift::Protocol::TProtocol & oprot);
};
} // NoteStore
} // EDAM
} // Evernote
