#pragma once

/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <windows.h>
#include <Thrift/Thrift.h>
#include <Thrift/Protocol.h>
#include <Thrift/Transport.h>

namespace Evernote
{
namespace EDAM
{
namespace Error
{
enum EDAMErrorCode
{
	UNKNOWN = 1,
	BAD_DATA_FORMAT = 2,
	PERMISSION_DENIED = 3,
	INTERNAL_ERROR = 4,
	DATA_REQUIRED = 5,
	LIMIT_REACHED = 6,
	QUOTA_REACHED = 7,
	INVALID_AUTH = 8,
	AUTH_EXPIRED = 9,
	DATA_CONFLICT = 10,
	ENML_VALIDATION = 11,
	SHARD_UNAVAILABLE = 12,
}
;
} // Error
} // EDAM
} // Evernote
