#pragma once

/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <windows.h>
#include <Thrift/Thrift.h>
#include <Thrift/Protocol.h>
#include <Thrift/Transport.h>


namespace Evernote
{
namespace EDAM
{
namespace Error
{

class EDAMUserException : public Thrift::TException
{
public:

	struct Isset
	{
		bool parameter;
	};

	EDAMErrorCode errorCode;
	Thrift::Protocol::TString parameter;

	Isset __isset;

	EDAMUserException();
	virtual ~EDAMUserException() throw() {}

	void Read(Thrift::Protocol::TProtocol & iprot);
	void Write(Thrift::Protocol::TProtocol & oprot);
};
} // Error
} // EDAM
} // Evernote
