/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include "../UserStore.h"
#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <windows.h>
#include <Thrift/Thrift.h>
#include <Thrift/Protocol.h>
#include <Thrift/Transport.h>
#include <Evernote/EDAM/Types.h>
#include <Evernote/EDAM/Error.h>

using namespace Evernote::EDAM::UserStore;

AuthenticationResult::AuthenticationResult()
{
	memset(&__isset, 0, sizeof(Isset));
}

void AuthenticationResult::Read(Thrift::Protocol::TProtocol & iprot)
{
	Thrift::Protocol::TStruct struc;
	iprot.ReadStructBegin(struc);
	for (;;)
	{
		Thrift::Protocol::TField field;
		iprot.ReadFieldBegin(field);
		if (field.GetType() == Thrift::Protocol::TypeStop)
			break;
		switch (field.GetID())
		{
		case 1:
			if (field.GetType() == Thrift::Protocol::TypeI64)
			{
				this->currentTime = iprot.ReadI64();
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 2:
			if (field.GetType() == Thrift::Protocol::TypeString)
			{
				this->authenticationToken;
				iprot.ReadString(this->authenticationToken);
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 3:
			if (field.GetType() == Thrift::Protocol::TypeI64)
			{
				this->expiration = iprot.ReadI64();
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 4:
			if (field.GetType() == Thrift::Protocol::TypeStruct)
			{
				this->user.Read(iprot);
				this->__isset.user = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		case 5:
			if (field.GetType() == Thrift::Protocol::TypeStruct)
			{
				this->publicUserInfo.Read(iprot);
				this->__isset.publicUserInfo = true;
			}
			else
			{
				Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			}
			break;
		default: 
			Thrift::Protocol::TProtocolUtil::Skip(iprot, field.GetType());
			break;
		}
		iprot.ReadFieldEnd();
	}
	iprot.ReadStructEnd();
}

void AuthenticationResult::Write(Thrift::Protocol::TProtocol & oprot)
{
	Thrift::Protocol::TStruct struc;
	struc.SetName(L"AuthenticationResult");
	oprot.WriteStructBegin(struc);
	{
		Thrift::Protocol::TField field;
		field.SetName(L"currentTime");
		field.SetType(Thrift::Protocol::TypeI64);
		field.SetID(1);
		oprot.WriteFieldBegin(field);
		oprot.WriteI64(this->currentTime);
		oprot.WriteFieldEnd();
	}
	{
		Thrift::Protocol::TField field;
		field.SetName(L"authenticationToken");
		field.SetType(Thrift::Protocol::TypeString);
		field.SetID(2);
		oprot.WriteFieldBegin(field);
		oprot.WriteString(this->authenticationToken);
		oprot.WriteFieldEnd();
	}
	{
		Thrift::Protocol::TField field;
		field.SetName(L"expiration");
		field.SetType(Thrift::Protocol::TypeI64);
		field.SetID(3);
		oprot.WriteFieldBegin(field);
		oprot.WriteI64(this->expiration);
		oprot.WriteFieldEnd();
	}
	if (__isset.user)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"user");
		field.SetType(Thrift::Protocol::TypeStruct);
		field.SetID(4);
		oprot.WriteFieldBegin(field);
		this->user.Write(oprot);
		oprot.WriteFieldEnd();
	}
	if (__isset.publicUserInfo)
	{
		Thrift::Protocol::TField field;
		field.SetName(L"publicUserInfo");
		field.SetType(Thrift::Protocol::TypeStruct);
		field.SetID(5);
		oprot.WriteFieldBegin(field);
		this->publicUserInfo.Write(oprot);
		oprot.WriteFieldEnd();
	}
	oprot.WriteFieldStop();
	oprot.WriteStructEnd();
}

