/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include "../UserStore.h"
#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <windows.h>
#include <Thrift/Thrift.h>
#include <Thrift/Protocol.h>
#include <Thrift/Transport.h>
#include <Evernote/EDAM/Type.h>
#include <Evernote/EDAM/Error.h>

using namespace Evernote::EDAM::UserStore;

Constants::Constants()
{
	EDAM_VERSION_MAJOR = 1;

	EDAM_VERSION_MINOR = 19;

}
