#pragma once

/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <windows.h>
#include <Thrift/Thrift.h>
#include <Thrift/Protocol.h>
#include <Thrift/Transport.h>
#include <Evernote/EDAM/Type.h>
#include <Evernote/EDAM/Error.h>

namespace Evernote
{
namespace EDAM
{
namespace UserStore
{
class Constants
{
public:
	Constants();

	__int16 EDAM_VERSION_MAJOR;
	__int16 EDAM_VERSION_MINOR;
};
const Constants constants;
} // UserStore
} // EDAM
} // Evernote
