#pragma once

/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <windows.h>
#include <Thrift/Thrift.h>
#include <Thrift/Protocol.h>
#include <Thrift/Transport.h>
#include <Evernote/EDAM/Types.h>
#include <Evernote/EDAM/Error.h>


namespace Evernote
{
namespace EDAM
{
namespace UserStore
{

class PublicUserInfo
{
public:

	struct Isset
	{
		bool privilege;
		bool username;
	};

	Evernote::EDAM::Types::UserID userId;
	Thrift::Protocol::TString shardId;
	Evernote::EDAM::Types::PrivilegeLevel privilege;
	Thrift::Protocol::TString username;

	Isset __isset;

	PublicUserInfo();
	virtual ~PublicUserInfo() throw() {}

	void Read(Thrift::Protocol::TProtocol & iprot);
	void Write(Thrift::Protocol::TProtocol & oprot);
};
} // UserStore
} // EDAM
} // Evernote
