#pragma once

/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <windows.h>
#include <Thrift/Thrift.h>
#include <Thrift/Protocol.h>
#include <Thrift/Transport.h>
#include <Evernote/EDAM/Limits.h>

namespace Evernote
{
namespace EDAM
{
namespace Type
{
enum PrivilegeLevel
{
	NORMAL = 1,
	PREMIUM = 3,
	MANAGER = 7,
	SUPPORT = 8,
	ADMIN = 9,
}
;
} // Type
} // EDAM
} // Evernote
